In [1]:
import pandas as pd
from os import listdir

In [48]:
#We can read the scraped files
read_all_1 = [pd.read_excel(f"shohrux/{file}") for file in listdir('shohrux') if file.endswith('.xlsx')]
read_all_2 = [pd.read_excel(f"sirojiddin/{file}") for file in listdir('sirojiddin') if file.endswith('.xlsx')]

df1 = pd.concat(read_all_1, axis=0,ignore_index=True)
df2 = pd.concat(read_all_2, axis=0,ignore_index=True)

In [49]:
#Checed df shape
print(f"df1 {df1.shape}")
print(f"df2 {df2.shape}")

df1 (110, 27)
df2 (100, 27)

In [40]:
df1.head()

,LABEL-1,LABEL-2,LABEL-3,LABEL-4,LABEL-5,LABEL-6,LABEL-7,LABEL-8,LABEL-9,LABEL-10,...,LABEL-18,LABEL-19,LABEL-20,LABEL-21,LABEL-22,LABEL-23,LABEL-24,LABEL-25,LABEL-26,LABEL-27
0,https://media.licdn.com/dms/image/D4D03AQHM0H7...,Status is offline,Umid Azamkulov,View Umid Azamkulov’s profile,• 2nd,2nd degree connection,• 2nd,2nd degree connection,Java Devoloper,"Tashkent Region, Uzbekistan",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://media.licdn.com/dms/image/C4E03AQHZcsL...,Status is offline,Akhad Abdullaev,View Akhad Abdullaev’s profile,• 2nd,2nd degree connection,• 2nd,2nd degree connection,Back-end Developer at DataSite Technology,"Tashkent Region, Uzbekistan",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://media.licdn.com/dms/image/C4D03AQF29VK...,Status is offline,Sardor Urdushev,View Sardor Urdushev’s profile,• 2nd,2nd degree connection,• 2nd,2nd degree connection,"Android Developer at ""Industrial and Construct...","Tashkent Region, Uzbekistan",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://media.licdn.com/dms/image/C4E03AQH9mqR...,Status is offline,Bekhruz Nutfilloev,View Bekhruz Nutfilloev’s profile,• 2nd,2nd degree connection,• 2nd,2nd degree connection,SDE @ Uzinfocom | DSAI @ Innopolis,"Tashkent Region, Uzbekistan",...,Message,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://media.licdn.com/dms/image/C4E03AQGVVxi...,Status is offline,Jasurbek Khajiev,View Jasurbek Khajiev’s profile,• 2nd,2nd degree connection,• 2nd,2nd degree connection,Data Engineer at EPAM Systems,Uzbekistan,...,Message,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
#The necessary columns for us
df1=df1[['LABEL-3','LABEL-9','LABEL-10','LABEL-1']]
df2=df2[['LABEL-3','LABEL-9','LABEL-10','LABEL-1']]

In [51]:
#Rename columns
df1.rename(columns={'LABEL-3':'Name','LABEL-9':'Profession','LABEL-10':'Location','LABEL-1':'Image'},inplace=True)
df2.rename(columns={'LABEL-3':'Name','LABEL-9':'Profession','LABEL-10':'Location','LABEL-1':'Image'},inplace=True)

In [52]:
#Drop duplicate values
df1.drop_duplicates(inplace=True)
df2.drop_duplicates(inplace=True)

In [53]:
# we combine data frames
df_new=pd.concat([df1,df2],axis=0,ignore_index=True)

In [54]:
df_new.duplicated().sum()

10

In [56]:
df_find_person=df_new[df_new.duplicated()==True]

In [57]:
df_find_person

,Name,Profession,Location,Image
103,Ibrokhim Turdiev,Backend & DevOps Engineer,Tashkent,https://media.licdn.com/dms/image/D4D03AQFgUnq...
104,Sabina Bilalova,"HR-manager, Bachelor University of Sunderland ...","Tashkent Region, Uzbekistan",https://media.licdn.com/dms/image/D4D03AQGdsyB...
105,Andrey Kosintsev,Machine Learning Engineer at EVRAZ,"Nur-Sultan, Kazakhstan",https://media.licdn.com/dms/image/D5603AQGBtnD...
106,Ozoda Bekmurodova,Recruitment Specialist – Person Hunters,Tashkent,https://media.licdn.com/dms/image/D4D03AQHKZQP...
107,G'avsiddin Vaxobjanov,Frontend (React JS and Next JS) developer | St...,"Namangan Region, Uzbekistan",https://media.licdn.com/dms/image/C4D03AQFuqTp...
108,Kirill Melnikov,Data/Product Analyst ex. ManyChat,Yerevan,https://media.licdn.com/dms/image/D4E03AQHfGIu...
109,Надира Ёдгорова,Human Resources Manager в компании Uzum,Tashkent,https://media.licdn.com/dms/image/C4E03AQGjlBh...
110,Ilya Khrushch,"Data Analyst, Data Science enthusiast","Mazowieckie, Poland",https://media.licdn.com/dms/image/C4D03AQEI6sl...
111,Sergey Seleznev,Experienced Project Manager and a Presale Cons...,"Almaty, Kazakhstan",https://media.licdn.com/dms/image/C4E03AQGOqan...
112,Dmitriy Ushakov,ML Engineer at Plesk,Sofia,NaN